version: '3.7'
services:
  ${PROJECT_NAME}-green:
    image: ${PROJECT_NAME}:green
    environment:
      - SERVICE_NAME=green
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes: []
    deploy:
      replicas: 2
    networks:
      - dbgr-net
    stop_signal: SIGTERM
    stop_grace_period: ${DOCKER_COMPOSE_STOP_GRACEFUL_SHUTDOWN_PERIOD}
networks:
  dbgr-net:
    external: true
