version: '3.7'
services:
  ${PROJECT_NAME}-green:
    image: spring-sample-h-auth:latest
    environment:
      - SERVICE_NAME=green
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes: []
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - consul
networks:
  consul:
    external: true
