FROM node:buster

RUN mkdir -p /usr/src/node-app && chown -R node:node /usr/src/node-app

WORKDIR /usr/src/node-app

COPY package.json yarn.lock ./

RUN chown -R node:node ./

# USER node

# RUN yarn install

# COPY --chown=node:node . .

EXPOSE 3000

WORKDIR /usr/src/node-app
ENTRYPOINT ["bash", "-c", "if [ ! -d 'node_modules' ]; then npm install; fi && npm run dev && /bin/bash"]
